### ISSUE TITLE
Extreme CPU usage using multiple projectors

### ISSUE THREAD

**Issue by RAKW** [amclain/duet-lib-pjlink#3]
Hi, 

I don't know if this is normal behaviour but running three instances of the library to control three projectors causes a cpu load average of 95% on my NI3000.

**Comment by amclain** [comment]
The NI-3000 is a pretty old unit; 2 generations behind the current model, the [NX-3200](https://trade.amx.com/products/NX-3200.asp). If I remember correctly, AMX published a note about how the NI-X000 controllers don't run Duet modules very well. The PJLink module does very little processing and spends most of its time sleeping, so I suspect that it's the overhead from the Java VM that's necessary to run Duet modules that's consuming most of the CPU. I've run four instances of the PJLink module on one of the NI-X100 units for a job without any CPU issues.

The first thing I recommend is upgrading the NI-3000's firmware. `3.60.453` appears to be the latest Duet version for that controller. If that doesn't work and you want to use the Duet module, I recommend upgrading the master to an NX-3200, which is the current model and _significantly_ faster. If you want to continue using the NI-3000, then serial communication to the projectors may be a better option if the master's CPU is overloaded by Duet.
